<?php

namespace mrstroz\wavecms\components\widgets;

use mihaildev\ckeditor\CKEditor;
use mihaildev\elfinder\ElFinder;

class CKEditorWidget extends CKEditor
{

    public function init()
    {
        if (!$this->editorOptions) {
            $this->editorOptions = ElFinder::ckeditorOptions(['elfinder'], [
                'preset' => 'full',
                'inline' => false,
                'toolbar' => [
                    ['Source'],
                    ['PasteText', '-', 'Undo', 'Redo'],
                    ['Replace', 'SelectAll', 'Scayt'],
                    ['Format', 'FontSize','Styles'],
                    ['Bold', 'Italic', 'Underline', 'TextColor', 'StrikeThrough', '-', 'Outdent', 'Indent', 'RemoveFormat',
                        'Blockquote', 'HorizontalRule'],
                    ['NumberedList', 'BulletedList', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight',
                        'JustifyBlock'],
                    ['Image', 'Embed', 'Video', 'Iframe'],
                    ['Table'],
                    ['Link', 'Unlink'],
                    ['Maximize', 'ShowBlocks'],

                ],
            ]);
        }

        parent::init();
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}
