<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Elements has been published' => 'Elementy zostały opublikowane',
    'Elements has been unpublished' => 'Elementom została cofnięta publikacja',
    '... choose action' => '... wybierz akcję',
    '<i>Not set</i>' => '<i>Nie ustawione</i>',
    'Are you sure ?' => 'Czy jesteś pewien ?',
    'Assets folders and cache has been cleared' => 'Foldery assets oraz cache zostały wyczyszczone',
    'Attribute {attribute} is not defined' => 'Atrybut {attribute} nie jest zdefiniowany',
    'Attribute {attribute} not found in model {model}' => 'Atrybut {attribute} nie znaleziony w modelu {model}',
    'Cache' => 'Cache',
    'Category' => 'Kategoria',
    'Clear assets folders and cache' => 'Wyczyść foldery assets oraz cache',
    'Component "wavecms" not defined in config.php' => 'Komponent "wavecms" nie zdefiniowany w pliku config.php',
    'Create new' => 'Utwórz nowy',
    'Dashboard' => 'Dashboard',
    'Delete' => 'Usuń',
    'Delete ?' => 'Usunąć ?',
    'Edited language has been changed to {lang}' => 'Edytowany język został zmieniony na {lang}',
    'Element has been created' => 'Element został utworzony',
    'Element has been deleted' => 'Element został usunięty',
    'Element has been updated' => 'Element został zaktualizowany',
    'Element not found' => 'Element nie został znaleziony',
    'Element will be displayed in following languages:' => 'Element zostanie wyświetlony w następujących językach:',
    'Elements cannot be moved down' => 'Element nie może zostać przeniesiony na dół',
    'Elements cannot be moved up' => 'Element nie może zostać przeniesiony do góry',
    'Elements from list "{heading}" has been deleted' => 'Elementy z listy "{heading}" zostały usunięte',
    'Elements has been deleted' => 'Elementy zostały usunięte',
    'Elements has been moved down' => 'Element został przeniesiony na dół',
    'Elements has been moved up' => 'Element został przeniesiony do góry',
    'Elements has not been choosed' => 'Żadne elementy nie zostały wybrane',
    'Height' => 'Wysokość',
    'ID' => 'ID',
    'Language' => 'Język',
    'Languages' => 'Języki',
    'Message' => 'Wiadomość',
    'Move down' => 'Przenieś na dół',
    'Move up' => 'Przenieś do góry',
    'No' => 'Nie',
    'Property "{property}" is not defined in {class}' => 'Właściwość "{property}" nie jest zdefiniowana dla {class}',
    'Property "attribute" is not defined in FileBehavior' => 'Właściwość "attribute" nie jest zdefiniowana dla FileBehavior',
    'Property "attribute" is not defined in ImageBehavior' => 'Właściwość "attribute" nie jest zdefiniowana dla ImageBehavior',
    'Property "languages" is not defined in config file for component "wavecms"' => 'Właściwość "languages" nie zdefiniowana w pliku config dla componentu "wavecms',
    'Property "listId" is not defined in SubListBehavior' => 'Właściwość "listId" nie jest zdefiniowana dla SubListBehavior',
    'Property "listId" is not defined in SubListWidget' => 'Właściwość "listId" nie jest zdefiniowana dla SubListWidget',
    'Property "model" is not defined in SubListWidget' => 'Właściwość "model" nie jest zdefiniowana dla SubListWidget',
    'Property "route" is not defined in SubListBehavior' => 'Właściwość "route" nie jest zdefiniowana dla SubListBehavior',
    'Property "sizes" is not defined in ImageBehavior' => 'Właściwość "sizes" nie jest zdefiniowana dla ImageBehavior',
    'Publish' => 'Publikuj',
    'Return' => 'Powrót',
    'Save' => 'Zapisz',
    'Save &amp; Return' => 'Zapisz i powróć',
    'Save changes to add sub list elements' => 'Zapisz zmiany by dodać elementy podlisty',
    'Settings' => 'Ustawienia',
    'Size is wrong defined for attribute {attribute}' => 'Wielkość jest źle zdefiniowana dla atrybutu {attribute}',
    'Submit' => 'Wyślij',
    'The "query" property is not instance of ActiveQuery.' => 'Właściwość "query" nie jest instancją ActiveQuery.',
    'The "query" property must be set.' => 'Właściwość "query" musi być zdefiniowana.',
    'Translation' => 'Tłumaczenie',
    'Translations' => 'Tłumaczenia',
    'Unpublish' => 'Cofnij publikację',
    'Welcome in wave<strong>CMS</strong>!' => 'Witaj w wave<strong>CMS</strong>!',
    'Width' => 'Szerokość',
    'Wrong language' => 'Zły język',
    'Yes' => 'Tak',
    'You are not allowed to perform this action' => 'Nie jesteś uprawniony do wykonania tej akcji',
];
