<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Aktywny',
    'Add permission' => 'Dodaj uprawnienie',
    'Add permission to role <b>{name}</b>' => 'Dodaj uprawnienia do roli <b>{name}</b>',
    'Add permissions' => 'Dodaj uprawnienia',
    'Assign role' => 'Przydziel rolę',
    'Assign role to user <b>{user}</b>' => 'Przydziel rolę do użytkownika <b>{user}</b>',
    'Assigned permissions' => 'Przydzielone uprawnienia',
    'Assigned roles' => 'Przydzielone role',
    'Back to login page' => 'Powrót do strony logowania',
    'Change password' => 'Zmień hasło',
    'Choose role' => 'Wybierz rolę',
    'Correctly logged out' => 'Poprawnie wylogowano',
    'Created at' => 'Utworzono',
    'Data' => 'Data',
    'Data has been changed' => 'Dane zostały zmienione',
    'Description' => 'Opis',
    'Email' => 'Email',
    'English' => 'Angielski',
    'First name' => 'Imię',
    'Forgot password ?' => 'Zapomniałeś hasła ?',
    'Incorrect username or password.' => 'Nie poprawny użytkownik bądź hasło',
    'Is admin ?' => 'Czy admin ?',
    'Language' => 'Język',
    'Last name' => 'Nazwisko',
    'Leave empty fields if you don\'t want to change password' => 'Zostaw puste pola jeśli nie chcesz zmieniać hasła',
    'List of users' => 'Lista użytkowników',
    'Login' => 'Zaloguj',
    'Login data' => 'Dane logowania',
    'Login to Wave<span>CMS</span>' => 'Zaloguj się do Wave<span>CMS</span>',
    'Login to WaveCMS' => 'Zaloguj się do WaveCMS',
    'Logout' => 'Wyloguj',
    'My account' => 'Moje konto',
    'Name' => 'Nazwa',
    'New password saved.' => 'Nowe hasło zostało zapisane.',
    'No' => 'Nie',
    'Not active' => 'Nie aktywny',
    'Password' => 'Hasło',
    'Password has been changed' => 'Hasło zostało zmienione',
    'Permission' => 'Uprawnienie',
    'Permission has been assigned' => 'Uprawnienie zostało przydzielone',
    'Permission has been revoked' => 'Uprawnienie zostało cofnięte',
    'Permission name' => 'Nazwa uprawnienia',
    'Permission not found' => 'Nie znaleziono uprawnienia',
    'Please check the email you provided for further instructions.' => 'Proszę o sprawdzenie wiadomości email z dalszymi instrukcjami.',
    'Please choose your new password:' => 'Proszę wprowadzić nowe hasło:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Proszę wprowadzić adres email. Link do zmiany hasła zostanie na niego wysłany.',
    'Please fix following errors:' => 'Prosimy poprawić następujące błędy:',
    'Polish' => 'Polski',
    'Remember me' => 'Zapamiętaj mnie',
    'Repeat password' => 'Powtórz hasło',
    'Reset password' => 'Resetuj hasło',
    'Role' => 'Rola',
    'Role has been assigned' => 'Rola została przydzielona',
    'Role has been created' => 'Rola została utworzona',
    'Role has been deleted' => 'Rola została usunięta',
    'Role has been revoked' => 'Rola została cofnięta',
    'Role has been updated' => 'Rola została zaktualizowana',
    'Role not found' => 'Nie znaleziono roli',
    'Roles' => 'Role',
    'Rule name' => 'Nazwa reguły',
    'Save' => 'Zapisz',
    'Save changes' => 'Zapisz zmiany',
    'Select role' => 'Wybierz rolę',
    'Send' => 'Wyślij',
    'Sorry, we are unable to reset password for the provided email address.' => 'Przepraszamy, ale nie jesteśmy w stanie wysłać wiadomości email na podany adres.',
    'Status' => 'Status',
    'Syntax: [module]/[controller]' => 'Składnia: [moduł]/[kontroler]',
    'There is no user with this email address.' => 'Nie ma użytkownika o podanym adresie email',
    'This email address has already been taken.' => 'Ten adres email jest już przydzielony',
    'This name has already been taken.' => 'Ta nazwa jest już przydzielona',
    'This permission is already assigned' => 'To uprawnienie jest już przydzielone',
    'This role is already assigned' => 'Ta rola jest już przydzielona',
    'Type' => 'Typ',
    'Updated at' => 'Zaktualizowano',
    'User assigned to "Super admin" role' => 'Użytkownik przydzielony do roli "Super admin"',
    'User data' => 'Dane użytkownika',
    'User has been created' => 'Użytkownik został utworzony',
    'User not found' => 'Nie znaleziono użytkownika',
    'Users' => 'Użytkownicy',
    'Yes' => 'Tak',
    '{super_admin} role cannot be changed' => 'Rola {super_admin} nie może zostać zmieniona',
    '{super_admin} role cannot be deleted' => 'Rola {super_admin} nie może zostać usunięta',
];
