<?php

namespace mrstroz\wavecms\components\actions;

use mrstroz\wavecms\components\web\Controller;
use Yii;
use yii\base\Action as BaseAction;
use yii\base\InvalidConfigException;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use yii\db\Query;
use yii\web\NotFoundHttpException;

/**
 * Action base class
 */
class Action extends BaseAction
{

    /**
     * @var Controller $controller
     */
    public $controller;

    /**
     * @var Query $query
     */
    public $query;

    /**
     * @var ActiveRecord $modelClass
     */
    public $modelClass;

    /**
     * @var string $tableName
     */
    public $tableName;


    /**
     * Init query and modelClass
     * @throws InvalidConfigException
     */
    public function init()
    {
        $this->query = $this->controller->query;
        if ($this->query) {
            $modelClass = Yii::createObject($this->query->modelClass);
            $this->modelClass = $modelClass;
            $this->tableName = $modelClass::tableName();
        }

        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * Function to get one model by id. Using in crete/update/page action
     * @param $id
     * @return ActiveRecord
     * @throws \yii\web\NotFoundHttpException
     * @throws InvalidConfigException
     */
    protected function _fetchOne($id)
    {

        /** @var ActiveRecord $model */
        $model = $this->query->andWhere([$this->tableName. '.id' => $id])->one();

        if (!$model)
            throw new NotFoundHttpException(Yii::t('wavecms/main', 'Element not found'));

        if ($this->controller->scenario) {
            $model->scenario = $this->controller->scenario;
        }

        return $model;
    }

    /**
     * Check if $this->query is set
     * @throws \yii\base\InvalidConfigException
     */
    protected function _checkConfig()
    {
        if (!$this->controller->query)
            throw new InvalidConfigException(Yii::t('wavecms/main', 'The "query" property must be set.'));

        if (!$this->controller->query instanceof ActiveQuery)
            throw new InvalidConfigException(Yii::t('wavecms/main', 'The "query" property is not instance of ActiveQuery.'));
    }

    /**
     *
     * @return array
     */
    protected function _forwardParams()
    {
        $return = [];

        foreach ($this->controller->forwardParams as $param) {
            $return[$param] = Yii::$app->request->get($param);
        }

        return $return;
    }
}